"""R38-04: make the corpus registry the single source of the corpus numbers.

The third review showed that the inventory table lists 11 identified entries summing to 5,035 records
while the text still claimed "nine assets, 4,933 records" — a residue of the earlier nine-row table,
with the record counts of two assets having been split since.

This script defines the registry once, states which assets enter the protocol-controlled analysis and
which are inventory-only, and emits (a) the LaTeX table, (b) the sentence numbers, so the text can be
generated rather than typed.

Outputs -> audit/r38/{corpus_registry.csv, corpus_numbers.json, table1_assets.tex}
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:                                                  # noqa: BLE001
    pass

ROOT = Path(__file__).resolve().parents[1]
AUD = ROOT / "audit" / "r38"
AUD.mkdir(parents=True, exist_ok=True)

# id, asset, relation role, identifier, repository, licence, records, in_analysis, participation, ref
ROWS = [
    ("uci_concrete", "UCI concrete compressive strength", "duplication (mix proportions)",
     "10.24432/C5PK67", "UCI ML Repository", "see repository terms", 1030, True,
     "regression (1 target) + duplication control", "data_uci_concrete"),
    ("lantsoght_sfrc", "SFRC beam shear database", "source-level (inventory only)",
     "10.5281/zenodo.2578061", "Zenodo", "see record", 488, False,
     "inventory and metadata audit only", "data_lantsoght_sfrc"),
    ("cfst_stub", "Stub CFST axial capacity", "proxy (section family)",
     "10.1038/s41598-024-53352-1", "Sci. Rep. + supplementary", "article licence", 1316, True,
     "regression (1 target) + feasibility boundary + narrowed holdout", "data_cfst_stub"),
    ("corroded_beam", "Corroded RC beam flexure", "source-level",
     "10.5281/zenodo.8062007", "Zenodo", "see record", 804, True,
     "regression (1 target) + decision experiment", "data_corroded_beam"),
    ("shear_wall_mode", "RC shear-wall failure mode", "source-level",
     "10.1016/j.engstruct.2020.110331", "Eng. Struct. + author database", "article licence", 393, True,
     "classification + decision experiment", "data_shear_wall_mode"),
    ("wall_prj2430", "UoA-UW RC wall database", "two relations (source + wall type)",
     "10.17603/ds2-r12q-t415", "DesignSafe-CI", "published project terms", 142, True,
     "regression (2 targets) + joint-claim case", "data_wall_prj2430"),
    ("coupling_prj3053", "Coupling-beam database", "source-level",
     "10.17603/ds2-46wc-n185", "DesignSafe-CI", "published project (PRJ-3053)", 60, True,
     "regression (1 target)", "data_coupling_prj3053"),
    ("columns_circular", "Circular RC columns", "inventory only",
     "10.17603/ds2-52bz-0n63", "DesignSafe-CI", "published project terms", 174, False,
     "inventory and metadata audit only", "data_rc_columns_circ"),
    ("columns_rectangular", "Rectangular RC columns", "inventory only",
     "10.17603/ds2-7qg0-4303", "DesignSafe-CI", "published project terms", 327, False,
     "inventory and metadata audit only", "data_rc_columns_rect"),
    ("joints_8ndgpm7zw7", "Exterior beam-column joints", "inventory only",
     "10.17632/8ndgpm7zw7.1", "Mendeley Data", "CC BY-NC 4.0 (DataCite)", 203, False,
     "inventory and metadata audit only", "data_joints_mendeley"),
    ("joints_rbhfnz32sy", "Beam-column joints, cyclic", "inventory only",
     "10.17632/rbhfnz32sy.1", "Mendeley Data", "CC BY 4.0 (DataCite)", 98, False,
     "inventory and metadata audit only", "data_joints_cyclic"),
]

n_assets = len(ROWS)
n_in = sum(1 for r in ROWS if r[7])
rec_total = sum(r[6] for r in ROWS)
rec_in = sum(r[6] for r in ROWS if r[7])
rec_out = rec_total - rec_in
numbers = {
    "assets_total": n_assets,
    "assets_in_analysis": n_in,
    "assets_inventory_only": n_assets - n_in,
    "records_total": rec_total,
    "records_in_analysis": rec_in,
    "records_inventory_only": rec_out,
    "regression_assets": n_in - 1,           # classification asset excluded
    "regression_configurations": 6,
}
(AUD / "corpus_numbers.json").write_text(json.dumps(numbers, indent=2), encoding="utf-8")

csv_lines = ["asset_id,asset,relation_role,identifier,repository,licence,records,in_analysis,participation,ref"]
for r in ROWS:
    csv_lines.append(",".join([r[0], f'"{r[1]}"', f'"{r[2]}"', r[3], f'"{r[4]}"', f'"{r[5]}"',
                               str(r[6]), str(r[7]).lower(), f'"{r[8]}"', r[9]]))
(AUD / "corpus_registry.csv").write_text("\n".join(csv_lines) + "\n", encoding="utf-8")

tex = ["% auto-generated by analysis/04_corpus_registry.py — do not edit by hand",
       r"\begin{table*}[htbp]", r"\centering",
       r"\caption{Corpus registry. Every identified entry is listed once, with the role its relation "
       r"plays, its identifier and the level at which it enters this study. Eleven entries totalling "
       rf"{rec_total:,} records are registered; {n_in} of them ({rec_in:,} records) supply the "
       rf"protocol-controlled analysis --- five assets for the six regression target configurations and "
       rf"a sixth for failure-mode classification --- while the remaining {n_assets - n_in} "
       rf"({rec_out:,} records) contribute to the inventory and metadata audit only. Record counts are "
       r"the counts listed at the source; filtered analysis counts differ where a target filter applies "
       r"and are recorded in the released registry. Licences marked ``verify at source'' were read from "
       r"the publisher page rather than from an API and are listed as recorded there.}",
       r"\label{tab:assets}", r"\tiny", r"\setlength{\tabcolsep}{3pt}",
       r"\begin{tabular}{p{4.6cm}p{3.3cm}p{2.6cm}p{2.2cm}rp{3.2cm}}", r"\toprule",
       r"Asset & Relation role & Identifier & Repository & Records & Participation \\", r"\midrule"]
for r in ROWS:
    cite = " \\citep{" + r[9] + "}" if r[9] else ""
    tex.append(f"{r[1]} & {r[2]} & \\texttt{{{r[3]}}} & {r[4]} & {r[6]:,} & {r[8]}{cite} \\\\")
tex += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
(ROOT / "manuscript" / "tables" / "table1_assets.tex").write_text("\n".join(tex) + "\n", encoding="utf-8")

print(json.dumps(numbers, indent=2))
print(f"\nwrote table1_assets.tex ({len(ROWS)} rows), corpus_registry.csv, corpus_numbers.json")
