"""R38-06: rebuild the two main results tables on the corrected definitions.

  * Table 4 (relation-stratified contrasts): stratum labels derived from the *asset* as well as the
    variant (the concrete asset's proxy key is a duplication relation, not a wall type), the concrete
    alias merged into one entry, unevaluated cells printed as "not evaluated" instead of nan, and the
    honoured R^2 column restored next to the two controls.
  * Table 5 (decision experiment): fold means plus the pooled counts behind them, so that the
    per-fold identity r_all = C * r_rel is not silently applied to averages.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:                                                  # noqa: BLE001
    pass

ROOT = Path(__file__).resolve().parents[1]
R36 = ROOT.parent / "R36_independent_review_rebuild_2026-09-16"
R37 = ROOT.parent / "R37_second_review_repair_2026-09-16"
TEX = ROOT / "manuscript" / "tables"
TEX.mkdir(parents=True, exist_ok=True)

PRETTY = {"stub_cfst": "Stub CFST", "corroded_rc_beam": "Corroded RC beam",
          "wall_prj2430_Vmax": "RC wall strength", "wall_prj2430_drift": "RC wall drift",
          "coupling_beams_prj3053": "Coupling beam", "concrete_strength": "Concrete (UCI)",
          "shear_wall_failure_mode": "Shear-wall failure mode"}

# stratum depends on the asset as well as on the variant name: the concrete asset's "proxy" key is a
# duplication relation, not a wall type, which is what the third review caught in the printed table.
STRATUM = {
    ("honoured", "*"): "source-level",
    ("wall_combo", "*"): "combination-unseen",
    ("honoured_proxy", "concrete_strength"): "duplication (8-input key)",
    ("uci_996_allinputs", "concrete_strength"): "duplication (8-input key) — alias of the proxy row",
    ("uci_428_ingredients", "concrete_strength"): "duplication (7-ingredient key)",
    ("honoured_proxy", "wall_prj2430_Vmax"): "proxy (wall type)",
    ("honoured_proxy", "wall_prj2430_drift"): "proxy (wall type)",
}


def stratum(variant: str, dataset: str) -> str:
    return STRATUM.get((variant, dataset), STRATUM.get((variant, "*"), variant))


pairs = pd.read_csv(R36 / "analysis/out/R36_control_pairs.csv")
adm = pairs[pairs["split_admissible"].fillna(False)].copy()
adm["stratum"] = [stratum(v, d) for v, d in zip(adm["variant"], adm["dataset"])]
# merge the alias: keep the row that carries a size-matched control, drop its duplicate
alias_mask = (adm["variant"] == "uci_996_allinputs") & (adm["dataset"] == "concrete_strength")
dropped = int(alias_mask.sum())
adm = adm[~alias_mask]


def num(x, fmt="{:+.3f}"):
    return "not evaluated" if pd.isna(x) else fmt.format(x)


rows = []
for _, r in adm.sort_values(["stratum", "dataset", "model"]).iterrows():
    rows.append(f"{r['stratum']} & {PRETTY.get(r['dataset'], r['dataset'])} & {r['model']} & "
                f"{int(r['K'])} & {r['r2_random5']:.3f} & "
                f"{'not evaluated' if pd.isna(r['r2_sizematch']) else format(r['r2_sizematch'], '.3f')} & "
                f"{r['r2_honoured']:.3f} & {num(r['delta_vs_sizematch'])} \\\\")
t2 = "\n".join([
    "% auto-generated by analysis/06_rebuild_main_tables_r38.py",
    r"\begin{table*}[htbp]", r"\centering",
    r"\caption{Relation-stratified contrasts. Each row is one asset, target relation, learner, split "
    r"and evaluated-record set. The concrete asset's eight-input key and its ``proxy'' label are the "
    rf"same evaluation and appear once; the alias row is removed, leaving {len(adm)} distinct entries. "
    r"``Not evaluated'' marks a comparison for which no size-matched control was computed, and such "
    r"rows take no part in any count or conclusion. $\Delta$ is honoured minus size-matched.}",
    r"\label{tab:contrasts}", r"\tiny", r"\setlength{\tabcolsep}{3pt}",
    r"\begin{tabular}{p{3.1cm}p{2.3cm}lp{1.4cm}rrrr}", r"\toprule",
    r"Relation stratum & Asset & Learner & $K$ & $R^2$ random & $R^2$ size-matched & $R^2$ honoured & "
    r"$\Delta$ \\", r"\midrule",
    *rows, r"\bottomrule", r"\end{tabular}", r"\end{table*}"])
(TEX / "table2_contrasts.tex").write_text(t2 + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Table 5: fold means + pooled
outer = pd.read_csv(R37 / "audit/r37/decision_outer.csv")
SCEN = {"beam_release": "Beam release", "failure_mode": "Failure mode"}
sel = outer[(outer.scenario == "beam_release") |
            ((outer.scenario == "failure_mode") & (outer.action_set == "release_when_not_dangerous"))]
rows5 = []
for (scen, proto, alpha), g in sel.groupby(["scenario", "protocol", "alpha"]):
    rows5.append(
        f"{SCEN[scen]} & {alpha:.2f} & {proto} & {g.inner_r_all.mean():.4f} & "
        f"{g.realised_r_all.mean():.4f} & {g.realised_r_all.mean() - g.inner_r_all.mean():+.4f} & "
        f"{g.realised_coverage.mean():.3f} & {g.realised_r_released.mean():.4f} & "
        f"{int(g.n_unsafe.sum())}/{int(g.n_released.sum())} & "
        f"{g.n_unsafe.sum() / g.n_released.sum():.4f} \\\\")
t5 = "\n".join([
    "% auto-generated by analysis/06_rebuild_main_tables_r38.py",
    r"\begin{table*}[htbp]", r"\centering",
    r"\caption{Engineering-decision experiment. Columns 4--8 are \emph{fold means} over the five outer "
    r"folds. Because $r_{\mathrm{all},k}=C_k r_{\mathrm{rel},k}$ holds per fold but not for averages, "
    r"the last two columns give the \emph{pooled} unsafe events over released records and the resulting "
    r"conditional risk; the two are not interchangeable. The failure-mode rows use the action set that "
    r"releases only when the predicted mode lies outside the scenario's designated family.}",
    r"\label{tab:decision}", r"\tiny", r"\setlength{\tabcolsep}{3pt}",
    r"\begin{tabular}{llrrrrrrrr}", r"\toprule",
    r"Scenario & $\alpha$ & protocol & est.\ $r_{\mathrm{all}}$ (fold mean) & realised "
    r"$r_{\mathrm{all}}$ (fold mean) & gap & coverage (fold mean) & $r_{\mathrm{rel}}$ (fold mean) & "
    r"pooled unsafe/released & pooled $r_{\mathrm{rel}}$ \\", r"\midrule",
    *rows5, r"\bottomrule", r"\end{tabular}", r"\end{table*}"])
(TEX / "table3_decision.tex").write_text(t5 + "\n", encoding="utf-8")

print(f"contrast table: {len(adm)} entries (alias rows removed: {dropped})")
print(f"decision table: {len(rows5)} rows")
print("\npooled check (beam, alpha=0.05):")
b = sel[(sel.scenario == "beam_release") & (sel.alpha == 0.05)]
for proto, g in b.groupby("protocol"):
    print(f"  {proto}: n_test {int(g.n_test.sum())}, n_released {int(g.n_released.sum())}, "
          f"n_unsafe {int(g.n_unsafe.sum())}, pooled r_rel {g.n_unsafe.sum()/g.n_released.sum():.4f}, "
          f"fold-mean r_rel {g.realised_r_released.mean():.4f}")
