"""R38-12: regenerate every table with geometry that survives the rendered page.

The geometry instrument (`analysis/11`) showed three distinct faults: `\\resizebox` shrinking type to
4.2--5.1 pt, tables whose natural width runs past the paper edge, and a figure whose internal font is
scaled down with it. The fix is structural:

  * wide tables go on landscape pages (`pdflscape`), where the text block is the page height;
  * narrow tables stay in portrait with wrapped `p{}` columns;
  * no table is scaled with `\\resizebox` any more;
  * body type stays at ``\\scriptsize`` (7--8 pt) or larger.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:                                                  # noqa: BLE001
    pass

ROOT = Path(__file__).resolve().parents[1]
R36 = ROOT.parent / "R36_independent_review_rebuild_2026-09-16"
R37 = ROOT.parent / "R37_second_review_repair_2026-09-16"
AUD38 = ROOT / "audit" / "r38"
TEX = ROOT / "manuscript" / "tables"
TEX.mkdir(parents=True, exist_ok=True)

PRETTY = {"stub_cfst": "Stub CFST", "corroded_rc_beam": "Corroded RC beam",
          "wall_prj2430_Vmax": "RC wall strength", "wall_prj2430_drift": "RC wall drift",
          "coupling_beams_prj3053": "Coupling beam", "concrete_strength": "Concrete (UCI)",
          "shear_wall_failure_mode": "Shear-wall failure mode"}
SHEET = "% auto-generated by analysis/12_rebuild_all_tables.py — do not edit by hand\n"


def landscape(body: str, caption: str, label: str, size: str = r"\scriptsize") -> str:
    return "\n".join([
        SHEET,
        r"\begin{landscape}",
        r"\begin{table}[p]", r"\centering",
        rf"\caption{{{caption}}}", rf"\label{{{label}}}", size,
        r"\setlength{\tabcolsep}{4pt}",
        body,
        r"\end{table}", r"\end{landscape}",
    ]) + "\n"


def portrait(body: str, caption: str, label: str, size: str = r"\footnotesize",
             span: bool = False) -> str:
    env = "table*" if span else "table"
    return "\n".join([
        SHEET,
        rf"\begin{{{env}}}[htbp]", r"\centering",
        rf"\caption{{{caption}}}", rf"\label{{{label}}}", size,
        r"\setlength{\tabcolsep}{4pt}",
        body,
        rf"\end{{{env}}}",
    ]) + "\n"


# ================================================================= 1. configuration registry
reg = pd.read_csv(R36 / "audit/r36/configuration_registry.csv")
KIND = {"source-level": "source-level", "proxy-family": "proxy (section family)",
        "duplication": "duplication (identical mix)"}
rows = []
for _, r in reg.iterrows():
    tgt = str(r["target"]).replace("_", r"\_")
    rows.append(f"{PRETTY.get(r['dataset'], r['dataset'])} & {tgt} & {int(r['n_raw'])} & "
                f"{int(r['n_analytic'])} & "
                f"{int(r['groups_postfilter']) if pd.notna(r['groups_postfilter']) else '--'} & "
                f"{KIND.get(r['relation_kind'], r['relation_kind'])} \\\\")
body = "\n".join([r"\begin{tabular}{p{3.4cm}p{2.6cm}rrrp{4.4cm}}", r"\toprule",
                  r"Dataset & Target & raw $n$ & analytic $n$ & groups & Relation \\", r"\midrule",
                  *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "table1_registry.tex").write_text(portrait(
    body,
    r"Configuration registry for the six regression configurations and the classification task. "
    r"``Relation'' states the provenance meaning in engineering terms, not the name of a code column; "
    r"group counts are post-filter counts read from the released group-size files.",
    "tab:registry"), encoding="utf-8")

# ================================================================= 2. relation semantics
rows = []
for _, r in reg.iterrows():
    meaning = str(r["relation_semantics"]).replace("_", r"\_")
    rows.append(f"{PRETTY.get(r['dataset'], r['dataset'])} & {KIND.get(r['relation_kind'], r['relation_kind'])} & "
                f"{meaning} \\\\")
body = "\n".join([r"\begin{tabular}{p{3.0cm}p{2.6cm}p{8.4cm}}", r"\toprule",
                  r"Dataset & Relation kind & Engineering meaning \\", r"\midrule",
                  *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "table5_relations.tex").write_text(portrait(
    body,
    r"Relation semantics. A splitter column named \texttt{source} does not make a section family a "
    r"source: the audited claim is defined by the engineering meaning recorded here, and a duplication "
    r"relation is never reported as a novelty claim.",
    "tab:relations"), encoding="utf-8")

# ================================================================= 3. corpus registry (landscape)
corpus = pd.read_csv(AUD38 / "corpus_registry.csv")
rows = []
for _, r in corpus.iterrows():
    cite = f" \\citep{{{r['ref']}}}" if isinstance(r["ref"], str) and r["ref"].strip() else ""
    rows.append(f"{r['asset']} & {r['relation_role']} & \\texttt{{{r['identifier']}}} & "
                f"{r['repository']} & {r['licence']} & {int(r['records']):,} & {r['participation']}{cite} \\\\")
body = "\n".join([r"\begin{tabular}{p{4.0cm}p{3.4cm}p{3.2cm}p{2.6cm}p{2.9cm}rp{5.6cm}}", r"\toprule",
                  r"Asset & Relation role & Identifier & Repository & Licence & Records & "
                  r"Participation \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "table1_assets.tex").write_text(landscape(
    body,
    r"Corpus registry. Every identified entry is listed once with the role its relation plays. Eleven "
    r"entries totalling 5{,}035 records are registered; six of them (3{,}745 records) supply the "
    r"protocol-controlled analysis --- five assets for the six regression target configurations and a "
    r"sixth for failure-mode classification --- while the remaining five (1{,}290 records) contribute "
    r"to the inventory and metadata audit only. Record counts are those listed at the source; filtered "
    r"analysis counts differ where a target filter applies and are recorded per configuration in the "
    r"released registry. Licences are as read from the publisher page and were not verified through an "
    r"API.",
    "tab:assets"), encoding="utf-8")

# ================================================================= 4. contrasts (landscape)
pairs = pd.read_csv(R36 / "analysis/out/R36_control_pairs.csv")
adm = pairs[pairs["split_admissible"].fillna(False)].copy()
STRATUM = {("honoured", "*"): "source-level", ("wall_combo", "*"): "combination-unseen",
           ("honoured_proxy", "concrete_strength"): "duplication (8-input key)",
           ("uci_428_ingredients", "concrete_strength"): "duplication (7-ingredient key)",
           ("honoured_proxy", "wall_prj2430_Vmax"): "proxy (wall type)",
           ("honoured_proxy", "wall_prj2430_drift"): "proxy (wall type)"}
adm["stratum"] = [STRATUM.get((v, d), STRATUM.get((v, "*"), v)) for v, d in zip(adm.variant, adm.dataset)]
adm = adm[~((adm.variant == "uci_996_allinputs") & (adm.dataset == "concrete_strength"))]
rows = []
for _, r in adm.sort_values(["stratum", "dataset", "model"]).iterrows():
    sm = "not evaluated" if pd.isna(r["r2_sizematch"]) else f"{r['r2_sizematch']:.3f}"
    dl = "not evaluated" if pd.isna(r["delta_vs_sizematch"]) else f"{r['delta_vs_sizematch']:+.3f}"
    rows.append(f"{r['stratum']} & {PRETTY.get(r['dataset'], r['dataset'])} & {r['model']} & "
                f"{int(r['K'])} & {r['r2_random5']:.3f} & {sm} & {r['r2_honoured']:.3f} & {dl} \\\\")
body = "\n".join([r"\begin{tabular}{p{3.6cm}p{3.0cm}p{2.9cm}rrrrp{1.9cm}}", r"\toprule",
                  r"Relation stratum & Asset & Learner & $K$ & $R^2$ random & $R^2$ size-matched & "
                  r"$R^2$ honoured & $\Delta$ \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "table2_contrasts.tex").write_text(landscape(
    body,
    rf"Relation-stratified contrasts. The concrete asset's eight-input key and its ``proxy'' label are "
    rf"the same evaluation and appear once, leaving {len(adm)} distinct entries. ``Not evaluated'' marks a "
    r"comparison for which no size-matched control was computed; such rows take no part in any count or "
    r"conclusion. $\Delta$ is honoured minus size-matched.",
    "tab:contrasts"), encoding="utf-8")

# ================================================================= 5. decision experiment (landscape)
outer = pd.read_csv(R37 / "audit/r37/decision_outer.csv")
SCEN = {"beam_release": "Beam release", "failure_mode": "Failure mode"}
sel = outer[(outer.scenario == "beam_release") |
            ((outer.scenario == "failure_mode") & (outer.action_set == "release_when_not_dangerous"))]
rows = []
for (scen, proto, alpha), g in sel.groupby(["scenario", "protocol", "alpha"]):
    rows.append(f"{SCEN[scen]} & {alpha:.2f} & {proto} & {g.inner_r_all.mean():.4f} & "
                f"{g.realised_r_all.mean():.4f} & {g.realised_r_all.mean() - g.inner_r_all.mean():+.4f} & "
                f"{g.realised_coverage.mean():.3f} & {g.realised_r_released.mean():.4f} & "
                f"{int(g.n_unsafe.sum())}/{int(g.n_released.sum())} & "
                f"{g.n_unsafe.sum() / g.n_released.sum():.4f} \\\\")
body = "\n".join([r"\begin{tabular}{llrrrrrrrr}", r"\toprule",
                  r"Scenario & $\alpha$ & protocol & est.\ $r_{\mathrm{all}}$ & realised "
                  r"$r_{\mathrm{all}}$ & gap & coverage & $r_{\mathrm{rel}}$ & pooled unsafe/released & "
                  r"pooled $r_{\mathrm{rel}}$ \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "table3_decision.tex").write_text(landscape(
    body,
    r"Engineering-decision experiment. Columns 4--8 are fold means over the five outer folds; because "
    r"$r_{\mathrm{all},k}=C_k r_{\mathrm{rel},k}$ holds per fold but not for averages, the last two "
    r"columns give the pooled unsafe events over released records and the resulting conditional risk. "
    r"The two are not interchangeable. The failure-mode rows use the action set that releases only when "
    r"the predicted mode lies outside the scenario's designated family.",
    "tab:decision"), encoding="utf-8")

# ================================================================= 6. SI: fold-size audit (landscape)
folds = pd.read_csv(R36 / "analysis/out/R36_fold_admissibility.csv")
SPLIT = {"honoured": "source", "honoured_proxy": "proxy", "wall_combo": "combo",
         "uci_428_ingredients": "7-ingr.", "uci_996_allinputs": "8-input (alias)",
         "random5": "random", "sizematch_relation": "size-match", "sizematch_proxy": "size-match",
         "dummy_trainmean": "train mean",
         "uci_428_ingredients_shuffledlabels": "7-ingr. shuffled",
         "uci_996_allinputs_shuffledlabels": "8-input shuffled"}
SHORT = {"stub_cfst": "CFST", "corroded_rc_beam": "Corroded beam", "wall_prj2430_Vmax": "Wall strength",
         "wall_prj2430_drift": "Wall drift", "coupling_beams_prj3053": "Coupling beam",
         "concrete_strength": "Concrete"}
rows = []
for _, r in folds.sort_values(["admissible", "dataset", "variant"]).iterrows():
    sizes = str(r["test_sizes"]).strip("[]").replace(", ", "/")
    rows.append(f"{SHORT.get(r['dataset'], r['dataset'])} & {SPLIT.get(r['variant'], r['variant'])} & "
                f"{int(r['K'])} & {int(r['n'])} & {int(r['L'])} & {int(r['U'])} & {sizes} & "
                f"{str(r['train_fraction_range']).replace('_', chr(92) + '_')} & {int(r['folds_below_L'])} & "
                f"{int(r['folds_above_U'])} & {'yes' if r['admissible'] else chr(92) + 'textbf{no}'} \\\\")
body = "\n".join([r"\begin{tabular}{llrrrrllrrc}", r"\toprule",
                  r"Dataset & Split & $K$ & $n$ & $L$ & $U$ & test sizes & train frac. & below $L$ & "
                  r"above $U$ & ok \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "tableS2_fold_admissibility.tex").write_text(landscape(
    body,
    r"Fold-size check for the 34 split variants executed in the protocol-controlled regression stage. "
    r"$L=\lceil 0.05n\rceil$, $U=\lfloor 0.50n\rfloor$. This table audits one of the three checks "
    r"defined in the main text; relation novelty and test coverage are reported separately, and the "
    r"classification splits, the nested decision experiment and the restricted CFST holdout are audited "
    r"in their own sections.",
    "tab:S2"), encoding="utf-8")

# ================================================================= 7. SI: full contrast table
# Eight columns as a longtable: 48 rows do not fit the landscape text block, so the table breaks across
# pages with a repeating header (the geometry check found the last rows off the paper before).
rows = []
for _, r in pairs.sort_values(["dataset", "variant", "model"]).iterrows():
    sm = f"{r['r2_sizematch']:.3f}" if pd.notna(r["r2_sizematch"]) else "--"
    dm = f"{r['delta_vs_sizematch']:+.3f}" if pd.notna(r["delta_vs_sizematch"]) else "--"
    verdict = "ok" if r["split_admissible"] else "fail"
    rows.append(f"{SHORT.get(r['dataset'], r['dataset'])} & {r['model']} & "
                f"{SPLIT.get(r['variant'], r['variant'])} ({int(r['K'])}; {verdict}) & "
                f"{r['r2_random5']:.3f} & {sm} & {r['r2_honoured']:.3f} & {dm} & "
                f"{r['fold_sd_r2']:.3f} \\\\")
head = ("Dataset & Learner & Split ($K$; check) & $R^2$ rnd & $R^2$ size-match & "
        "$R^2$ hon. & $\\Delta$ & fold sd \\\\")
s1 = "\n".join([
    SHEET, r"\begin{landscape}", r"\begin{longtable}{p{2.0cm}p{2.3cm}p{3.1cm}rrrrr}",
    r"\caption{Every honoured contrast computed in this study. A split marked \emph{fail} does not "
    r"satisfy the fold-size check and carries no performance claim. The concrete asset's eight-input key "
    r"and its proxy label are the same evaluation, so the admissible set holds 32 distinct entries "
    r"rather than 36 rows.}\label{tab:S1}\\", r"\toprule", head, r"\midrule", r"\endfirsthead",
    r"\multicolumn{8}{l}{\small\emph{Table \ref{tab:S1} continued}}\\ \toprule", head, r"\midrule",
    r"\endhead", r"\bottomrule", r"\endlastfoot", *rows, r"\end{longtable}", r"\end{landscape}"])
(TEX / "tableS1_all_contrasts.tex").write_text(s1 + "\n", encoding="utf-8")

# ================================================================= 8. SI: outer-fold longtable
# Ten columns: the action set is folded into the scenario label and the chosen rule is carried by
# Table S5, so the row fits the landscape text block.
lines = [SHEET, r"\begin{landscape}", r"\begin{longtable}{p{2.6cm}p{2.0cm}p{1.7cm}rrrrrrr}",
         r"\caption{Outer-fold record of the decision experiment. Every fold reports its evaluated "
         r"rows, released rows, unsafe events and both risk denominators. The chosen rule for each fold "
         r"is listed in Table~\ref{tab:S5}.}\label{tab:S3}\\", r"\toprule",
         r"Scenario (action set) & protocol & fold & $\alpha$ & est. & real. & $n_{\rm test}$ & "
         r"$n_{\rm rel}$ & $n_{\rm unsafe}$ & coverage \\", r"\midrule", r"\endfirsthead",
         r"\multicolumn{10}{l}{\small\emph{Table \ref{tab:S3} continued}}\\ \toprule",
         r"Scenario (action set) & protocol & fold & $\alpha$ & est. & real. & $n_{\rm test}$ & "
         r"$n_{\rm rel}$ & $n_{\rm unsafe}$ & coverage \\", r"\midrule", r"\endhead",
         r"\bottomrule", r"\endlastfoot"]
for _, r in outer.sort_values(["scenario", "action_set", "protocol", "outer_fold", "alpha"]).iterrows():
    aset = {"act_on_confidence": "any-conf", "release_when_not_dangerous": "non-dangerous"}.get(
        r.get("action_set", ""), "-")
    lines.append(f"{SCEN[r['scenario']]} ({aset}) & {r['protocol']} & {int(r['outer_fold'])} & "
                 f"{r['alpha']:.2f} & {r['inner_r_all']:.4f} & {r['realised_r_all']:.4f} & "
                 f"{int(r['n_test'])} & {int(r['n_released'])} & {int(r['n_unsafe'])} & "
                 f"{r['realised_coverage']:.3f} \\\\")
lines += [r"\end{longtable}", r"\end{landscape}"]
(TEX / "tableS3_decision_folds.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

# ================================================================= 9. SI: candidate rules (portrait)
cand = pd.read_csv(R37 / "audit/r37/decision_candidates.csv")
chosen = cand[cand["chosen"]].sort_values(["scenario", "protocol", "outer_fold", "alpha"]).head(10)
rows = []
for _, r in chosen.iterrows():
    mask = ((cand.scenario == r["scenario"]) & (cand.protocol == r["protocol"]) &
            (cand.outer_fold == r["outer_fold"]) & (cand.alpha == r["alpha"]))
    n_feas, n_all = int(cand[mask]["feasible"].sum()), int(mask.sum())
    knob = r["margin"] if pd.notna(r.get("margin")) else r.get("confidence")
    rows.append(f"{r['scenario'].replace('_', ' ')} & {r['protocol']} & {int(r['outer_fold'])} & "
                f"{r['alpha']:.2f} & {r['model']}/{knob} & {r['inner_r_all']:.4f} & "
                f"{r['inner_coverage']:.3f} & {'all' if n_feas == n_all else f'{n_feas}/{n_all}'} \\\\")
body = "\n".join([r"\begin{tabular}{llrrlrrl}", r"\toprule",
                  r"Scenario & protocol & fold & $\alpha$ & chosen rule & inner $r_{\mathrm{all}}$ & "
                  r"coverage & feasible \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}"])
(TEX / "tableS5_candidate_rules.tex").write_text(portrait(
    body,
    r"Candidate rules and the selection actually made (first ten outer folds; the complete table is "
    r"released with the audit). ``feasible'' counts the candidate rules whose inner "
    r"$r_{\mathrm{all}}$ met the target, so an inactive constraint appears as ``all''.",
    "tab:S5"), encoding="utf-8")

print("rewrote:", sorted(p.name for p in TEX.glob("table*.tex")))
