"""R38-20: tables taller than a landscape page must break across pages.

The geometry check found SI Table S1 running to y = 704.8 pt on a 612 pt page: 48 rows at \\scriptsize
need about 580 pt, which does not fit the landscape text height, so the last rows were off the paper.
Table S1 becomes a longtable (repeating header). Every landscape table is checked for the same fault and
converted where needed.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import pymupdf

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:                                                  # noqa: BLE001
    pass

ROOT = Path(__file__).resolve().parents[1]
MAN = ROOT / "manuscript"
TEX = MAN / "tables"

# ---------------------------------------------------------------- S1 -> longtable
p = TEX / "tableS1_all_contrasts.tex"
t = p.read_text(encoding="utf-8")
m = re.search(r"\\begin\{landscape\}\s*\\begin\{table\}\[p\](.*?)\\end\{table\}\s*\\end\{landscape\}",
              t, re.S)
if not m:
    print("S1 structure not as expected; aborting")
    sys.exit(1)
body = m.group(1)
caption = re.search(r"\\caption\{(.*?)\}\s*\\label", body, re.S).group(1)
rows = [ln for ln in body.splitlines() if ln.rstrip().endswith(r"\\") and "&" in ln]
header_spec = r"lllcrrrr"
lines = [r"% auto-generated by analysis/20_longtable_fix.py",
         r"\begin{landscape}", rf"\begin{{longtable}}{{{header_spec}}}",
         rf"\caption{{{caption}}}", r"\label{tab:S1}\\", r"\toprule",
         r"Dataset & Learner & Split (fold-size check, $K$) & $R^2$ rnd & $R^2$ size-match & "
         r"$R^2$ hon. & $\Delta$ & fold sd \\", r"\midrule", r"\endfirsthead",
         r"\multicolumn{8}{l}{\small\emph{Table \ref{tab:S1} continued}}\\ \toprule",
         r"Dataset & Learner & Split (fold-size check, $K$) & $R^2$ rnd & $R^2$ size-match & "
         r"$R^2$ hon. & $\Delta$ & fold sd \\", r"\midrule", r"\endhead",
         r"\bottomrule", r"\endlastfoot", *rows, r"\end{longtable}", r"\end{landscape}"]
p.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Table S1 converted to a longtable with {len(rows)} rows")

# ---------------------------------------------------------------- measure every landscape table
doc = pymupdf.open(MAN / "si.pdf")
print("\nlandscape pages in the current SI and their text extents:")
for pno, page in enumerate(doc, 1):
    if page.rect.width > page.rect.height:
        spans = [s for b in page.get_text("dict")["blocks"] for l in b.get("lines", [])
                 for s in l["spans"] if s["text"].strip()]
        ys1 = max(s["bbox"][3] for s in spans)
        print(f"  page {pno}: page {page.rect.width:.0f}x{page.rect.height:.0f}, "
              f"text ends at y={ys1:.1f} ({'OVERFLOW' if ys1 > page.rect.height - 20 else 'fits'})")
doc.close()
